### ISSUE TITLE
Add "Hide giveaway" for single giveaways

### ISSUE THREAD

**Issue by tragikos** [leomoty/SGV2-#14]
When you don't want to enter a giveaway, it would be nice if you could just hide it until it ends.

Buttons both on main page next to each giveaway and inside it's giveaway's page would be appreciated.

**Comment by Djfe** [comment]
:+1:

**Comment by Djfe** [comment]
more suitable to post it here: http://www.steamgifts.com/discussion/tjnSG/hide-giveaways-ive-already-entered

it's more a suggestion for sg rather than in sg++
(easier to solve server-wise, this just a client script)
