### ISSUE TITLE
text shadow -> marked text looks blurry

### ISSUE THREAD

**Issue by Djfe** [leomoty/SGV2-#29]
do you really want to keep the following css rule?
.page__outer-wrap {
    text-shadow: 1px 1px rgba(255, 255, 255, 0.94);
}

the effect is barely obvious when the text is unmarked (small white text shadow for comments and stuff) -> the text looks pretty crisp

but when you mark it the whole text including their shadow is going white, so that it looks blurry (you can see both lines on top of each other making it harder to read)

::selection/::moz-selection should help you ;)

http://stackoverflow.com/questions/13027452/css-to-remove-text-shadow-on-select-highlight-text-mozilla

**Comment by leomoty** [comment]
Can you add me to steam? I am interested in changing, consider that some of this stuff was done in SGv2+ beta over a year ago... While there were about 30 members on site at most.

**Comment by Djfe** [comment]
your name on steam is leomoty, too right?
